services:
   web:
     image: nginx:stable-bookworm
     container_name: nginx
     ports:
       - "9090:90"
     volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       - ./src:/var/www/
   app:
     build:
       context: ./php
     container_name: fpm
     volumes:
       - ./src:/var/www/
   db:
    image: mysql:8.0
    platform: linux/x86_64 
    container_name: db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 6606:3306
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: true
       MYSQL_DATABASE: auto_music
       LANG: C.UTF-8
volumes:
  mysql: